### ISSUE TITLE
Error with sourcemaps in 1.3.6

### ISSUE THREAD

**Issue by unclechu** [stevelacy/gulp-stylus#108]
I have error with sourcemaps by options:
```javascript
options.sourcemap = {
  inline: true,
  sourceRoot: '.',
  basePath: path.join(srcDir)
};
```
I have errors like this:
```
Potentially unhandled rejection [3] Error: ENOENT, open 'main.styl'
```
And this:
```
[13:45:37] Error in plugin 'gulp-stylus'
Message:
    ENOENT, open 'main.styl'
Details:
    errno: 34
    code: ENOENT
    path: main.styl
Potentially unhandled rejection [3] TypeError: Cannot read property 'result' of undefined
    at .../node_modules/gulp-stylus/index.js:37:14
    at tryCatchReject (.../node_modules/gulp-stylus/node_modules/accord/node_modules/when/lib/makePromise.js:840:30)
    at runContinuation1 (.../node_modules/gulp-stylus/node_modules/accord/node_modules/when/lib/makePromise.js:799:4)
    at Fulfilled.when (.../node_modules/gulp-stylus/node_modules/accord/node_modules/when/lib/makePromise.js:590:4)
    at Pending.run (.../node_modules/gulp-stylus/node_modules/accord/node_modules/when/lib/makePromise.js:481:13)
    at Scheduler._drain (.../node_modules/gulp-stylus/node_modules/accord/node_modules/when/lib/Scheduler.js:62:19)
    at Scheduler.drain (.../node_modules/gulp-stylus/node_modules/accord/node_modules/when/lib/Scheduler.js:27:9)
    at process._tickCallback (node.js:419:13)
```

**Comment by jenius** [comment]
This is the incorrect way to produce sourcemaps. The way to use sourcemaps is outlines clearly in the readme and example docs. [You can find it here](https://github.com/stevelacy/gulp-stylus/blob/master/examples/gulpfile.js#L45) :grinning:

**Comment by unclechu** [comment]
@jenius ok, but it was supported in 1.x earlier, and now it broke backward compatibility in another 1.x. Do you follow semver? If answer is 'yes' then you must update major version to 2 when you removed support of old style of using sourcemaps.

**Comment by jenius** [comment]
Fair enough. Honestly I'm not sure how the original implementation worked, it was something of a hack job while we worked on actual sourcemap support. But you're right, we should add backwards compatibility or make a major version bump. @stevelacy probably would have some thoughts about this too.

**Comment by stevelacy** [comment]
This happened with gulp-less, I will publish to 2.0.0 and 1.3.7

**Comment by neonstalwart** [comment]
so, before i go updating... will 1.3.7 work like 1.3.5 or what?

**Comment by unclechu** [comment]
@jenius I recommend create fix release 1.3.(7) with backport sourcemap support, and immideately create 2 release with new sourcemaps (without sourcemaps backport).

**Comment by neonstalwart** [comment]
ugh... 1.3.5 doesn't even exist it seems

**Comment by stevelacy** [comment]
@unclechu that is what I will do, as stated

**Comment by jenius** [comment]
@unclechu @stevelacy -- agreed, that seems like the correct approach to me!

**Comment by stevelacy** [comment]
v1.3.7 + v2.0.0 published
