### ISSUE TITLE
gulp-stylus doesn't work after upgrading nodejs to v4.0

### ISSUE THREAD

**Issue by Archiolidius** [stevelacy/gulp-stylus#141]
The gulp-stylus compilation doesn't work after upgrading nodejs to version 4.0. Here is stacktrace:
```
Potentially unhandled rejection [2] Error: no writecb in Transform class
    at afterTransform (/Users/intouch/Projects/RedBull/redbull-gemini/node_modules/gulp-stylus/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:76:33)
    at TransformState.afterTransform (/Users/intouch/Projects/RedBull/redbull-gemini/node_modules/gulp-stylus/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:59:12)
    at /Users/intouch/Projects/RedBull/redbull-gemini/node_modules/gulp-stylus/index.js:47:16
    at tryCatchReject (/Users/intouch/Projects/RedBull/redbull-gemini/node_modules/gulp-stylus/node_modules/accord/node_modules/when/lib/makePromise.js:845:30)
    at runContinuation1 (/Users/intouch/Projects/RedBull/redbull-gemini/node_modules/gulp-stylus/node_modules/accord/node_modules/when/lib/makePromise.js:804:4)
    at Rejected.when (/Users/intouch/Projects/RedBull/redbull-gemini/node_modules/gulp-stylus/node_modules/accord/node_modules/when/lib/makePromise.js:625:4)
    at Pending.run (/Users/intouch/Projects/RedBull/redbull-gemini/node_modules/gulp-stylus/node_modules/accord/node_modules/when/lib/makePromise.js:483:13)
    at Scheduler._drain (/Users/intouch/Projects/RedBull/redbull-gemini/node_modules/gulp-stylus/node_modules/accord/node_modules/when/lib/Scheduler.js:62:19)
    at Scheduler.drain (/Users/intouch/Projects/RedBull/redbull-gemini/node_modules/gulp-stylus/node_modules/accord/node_modules/when/lib/Scheduler.js:27:9)
    at doNTCallback0 (node.js:407:9)
```

**Comment by stevelacy** [comment]
Added tests for node v4: https://travis-ci.org/stevelacy/gulp-stylus/jobs/80285104
Passing

**Comment by Archiolidius** [comment]
Sorry, gulp-stylus works fine. The problem is with another lib: https://github.com/konitter/gulp-combine-media-queries/issues/20
