### ISSUE TITLE
TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by lamartire** [stevelacy/gulp-stylus#180]
Hello!

When i try to compile styl files gulp throw heap of errors:
```
[11:49:36] Starting 'styles'...
[11:49:36] 'styles' errored after 3.74 ms
[11:49:36] TypeError: Cannot read property 'length' of undefined
at flattenGlob (/home/kot/Рабочий стол/react-starterify/node_modules/glob2base/index.js:9:25)
at setToBase (/home/kot/Рабочий стол/react-starterify/node_modules/glob2base/index.js:48:12)
at module.exports (/home/kot/Рабочий стол/react-starterify/node_modules/glob2base/index.js:56:19)
at Object.gs.createStream (/home/kot/Рабочий стол/react-starterify/node_modules/glob-stream/index.js:34:42)
at Object.gs.create (/home/kot/Рабочий стол/react-starterify/node_modules/glob-stream/index.js:68:42)
at Gulp.src (/home/kot/Рабочий стол/react-starterify/node_modules/vinyl-fs/lib/src/index.js:33:23)
at Gulp.<anonymous> (gulpfile.babel.js:92:15)
at module.exports (/home/kot/Рабочий стол/react-starterify/node_modules/orchestrator/lib/runTask.js:34:7)
at Gulp.Orchestrator._runTask (/home/kot/Рабочий стол/react-starterify/node_modules/orchestrator/index.js:273:3)
at Gulp.Orchestrator._runStep (/home/kot/Рабочий стол/react-starterify/node_modules/orchestrator/index.js:214:10)
at Gulp.Orchestrator.start (/home/kot/Рабочий стол/react-starterify/node_modules/orchestrator/index.js:134:8)
at /usr/lib/node_modules/gulp/bin/gulp.js:129:20
at _combinedTickCallback (internal/process/next_tick.js:67:7)
at process._tickCallback (internal/process/next_tick.js:98:9)
at Module.runMain (module.js:592:11)
at run (bootstrap_node.js:394:7)
```

`gulp-stylus` version **2.5.0**

Stylus gulp task:
```
gulp.task('styles', () => {
  return gulp.src('src/styles/main.styl', {base: ''})
  .pipe(stylus({
    use: [rupture()]
  }))
  .pipe(postcss([autoprefixer, cssnano]))
  .pipe(gulp.dest('dist/styles'), {overwrite: true})
  .pipe(reload({ stream: true }));
});
```

FIles structure:
![](http://dl1.joxi.net/drive/2016/08/22/0016/3508/1093044/44/8f012d6ce3.jpg)

**Comment by lamartire** [comment]
@stevelacy, yeah, you right. Reinstall stylus packages helped me. Thanks :+1:
