### ISSUE TITLE
Error: 'tried to require: stylus'.

### ISSUE THREAD

**Issue by jvijayasarathygit** [stevelacy/gulp-stylus#199]
Hi 

We are also facing similar issue. We are using NodeJS 4.8.4. Please help us to resolve this issue. Any other alternative also we are ready to try.

gulp-stylus@2.7.0 node_modules/gulp-stylus
+-- replace-ext@0.0.1
+-- lodash.assign@3.2.0 (lodash._baseassign@3.2.0, lodash.keys@3.1.2, lodash._createassigner@3.1.1)
+-- plugin-error@0.1.2 (arr-union@2.1.0, ansi-red@0.1.1, ansi-cyan@0.1.1, extend-shallow@1.1.4, arr-diff@1.1.0)
+-- vinyl-sourcemaps-apply@0.2.1 (source-map@0.5.7)
+-- through2@2.0.5 (xtend@4.0.1, readable-stream@2.3.6)
+-- accord@0.26.4 (lodash.flatten@4.4.0, lodash.pick@4.4.0, lodash.defaults@4.2.0, lodash.uniq@4.5.0, lodash.partialright@4.2.1, lodash.clone@4.5.0, lodash.merge@4.6.1, indx@0.2.3, semver@5.6.0, convert-source-map@1.6.0, glob@7.1.3, when@3.7.8, resolve@1.8.1, uglify-js@2.8.29)

+ gulp test
/opt/jenkins/workspace/ANZO/Guidewire/PortalFrontEnd/OctoberRelease2018-807d/source/node_modules/gulp-stylus/node_modules/accord/lib/adapter_base.js:105
        throw new Error("'tried to require: " + this.supportedEngines + "'.\nNone found. Make sure one has been installed!");
        ^

Error: 'tried to require: stylus'.
None found. Make sure one has been installed!
    at Stylus.Adapter (/opt/jenkins/workspace/ANZO/Guidewire/PortalFrontEnd/OctoberRelease2018-807d/source/node_modules/gulp-stylus/node_modules/accord/lib/adapter_base.js:105:15)
    at new Stylus (/opt/jenkins/workspace/ANZO/Guidewire/PortalFrontEnd/OctoberRelease2018-807d/source/node_modules/gulp-stylus/node_modules/accord/lib/adapters/stylus/0.x.js:19:43)
    at Object.exports.load (/opt/jenkins/workspace/ANZO/Guidewire/PortalFrontEnd/OctoberRelease2018-807d/source/node_modules/gulp-stylus/node_modules/accord/lib/index.js:31:12)
    at Object.<anonymous> (/opt/jenkins/workspace/ANZO/Guidewire/PortalFrontEnd/OctoberRelease2018-807d/source/node_modules/gulp-stylus/index.js:4:40)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)

**Comment by stevelacy** [comment]
#198
